# Connection details for proxy
Proxy:  False
ProxyURL: "127.0.0.1:8008"
RewardAddress:  "0x0000000000000000000000000000000000000001"
Password: "password"

# Connection details for solo mining
Location: [0,0]
PrimeURL: "ws://127.0.0.1:8001"
RegionURLs: ["ws://127.0.0.1:8002", "ws://127.0.0.1:8003", "ws://127.0.0.1:8004"]
ZoneURLs: [["ws://127.0.0.1:8100", "ws://127.0.0.1:8101", "ws://127.0.0.1:8102"], ["ws://127.0.0.1:8120", "ws://127.0.0.1:8121", "ws://127.0.0.1:8122"], ["ws://127.0.0.1:8140", "ws://127.0.0.1:8141", "ws://127.0.0.1:8142"] ]
RunBlake3: True
